### ISSUE TITLE
GUI not updating when setting contour controls from scripted client

### ISSUE THREAD

**Issue by durga2112** [Astroua/CARTAvis#109]
This is similar to past issues with both the colormap (#25) and histogram (#19).

Here are some scripted commands that will demonstrate the problem. First of all, to get the application started, follow the instructions at the beginning of [this iPython notebook](http://nbviewer.ipython.org/gist/durga2112/e65c09de5999315865f5/demo.ipynb). If you have a favourite image for contours, set the `imageFile` variable to point to that image. Now try the following commands:

```python
i = v.getImageViews()

i[0].setContourLevelMin(10)
# Note that this triggers an error.

i[0].setContourLevelMax(90)
i[0].setContourLevelMin(10)
# Now it works, so it is clear that these values are being stored,
# even if they can't be seen in the GUI.

i[0].setContourLevelCount(5)
# Again, this does not show up in the GUI.

i[0].generateContourSet('contour1')
# The contours show up on the image, even if the text boxes, etc. 
# do not reflect the proper values (or any values at all)
```

**Comment by durga2112** [comment]
I forgot that the code for the above commands is not in the develop branch yet. I just submitted a PR to get the code in; you can also just compile from the jeff branch to get the code.

**Comment by slovelan** [comment]
I believe this is not a bug, but working as expected.  First, setContourLevelMin should generate an error since you are trying to set a minimum contour level less than the maximum.  Second, you will notice that when you report that the GUI is not updating that you are looking at the "Default" which is
the screen used for generating a contour set.  If you change the combo box to 'contour1', which is 
the one you generated, you will see the values you set.

**Comment by durga2112** [comment]
Okay, that works for me. I never thought about what was actually in the combo box, but that makes sense. I'll close this issue.
